version: '3'

services:
  mcp-server:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GEOTAB_USERNAME=${GEOTAB_USERNAME}
      - GEOTAB_PASSWORD=${GEOTAB_PASSWORD}
      - GEOTAB_DATABASE=${GEOTAB_DATABASE}
      - GEOTAB_SERVER=${GEOTAB_SERVER}
      - MCP_HOST=0.0.0.0
      - MCP_PORT=8000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
